export const scheduleDataTable = [
    { id: "1", title: "Engineering Operations Management", room: "M328", building: "George Moore", floor: "Third Floor", day: "Monday", time: "9:00 AM" },
    { id: "2", title: "Communications", room: "M331", building: "George Moore", floor: "Third Floor", day: "Monday", time: "11:00 AM" },
    { id: "3", title: "European Project Semester", room: "M321A", building: "George Moore", floor: "Third Floor", day: "Wednesday", time: "2:00 PM" },
    { id: "4", title: "Innovation and Entrepreneurship", room: "M316", building: "George Moore", floor: "Third Floor", day: "Thursday", time: "10:00 AM" },
    { id: "5", title: "European Project Semester", room: "M327A", building: "George Moore", floor: "Third Floor", day: "Friday", time: "1:00 PM" },
    { id: "6", title: "European Project Semester", room: "M320", building: "George Moore", floor: "Third Floor", day: "Wednesday", time: "2:00 PM" },
    { id: "7", title: "Innovation and Entrepreneurship", room: "M317", building: "George Moore", floor: "Third Floor", day: "Thursday", time: "10:00 AM" },
    { id: "8", title: "European Project Semester", room: "M303", building: "George Moore", floor: "Third Floor", day: "Friday", time: "1:00 PM" },
    { id: "9", title: "Advanced Algorithms", room: "M323A", building: "George Moore", floor: "Third Floor", day: "Monday", time: "9:00 AM" },
    { id: "10", title: "Database Systems", room: "M301G", building: "George Moore", floor: "Third Floor", day: "Tuesday", time: "10:00 AM" },
    { id: "11", title: "Software Engineering", room: "M301F", building: "George Moore", floor: "Third Floor", day: "Wednesday", time: "11:00 AM" },
    { id: "12", title: "Web Development", room: "M301E", building: "George Moore", floor: "Third Floor", day: "Thursday", time: "1:00 PM" },
    { id: "13", title: "Computer Networks", room: "M301H", building: "George Moore", floor: "Third Floor", day: "Friday", time: "2:00 PM" },
    { id: "14", title: "Data Science", room: "M301D", building: "George Moore", floor: "Third Floor", day: "Monday", time: "3:00 PM" },
    { id: "15", title: "Machine Learning", room: "M301C", building: "George Moore", floor: "Third Floor", day: "Tuesday", time: "9:00 AM" },
    { id: "16", title: "Cybersecurity", room: "M301I", building: "George Moore", floor: "Third Floor", day: "Wednesday", time: "10:00 AM" },
    { id: "17", title: "AI Ethics", room: "M301B", building: "George Moore", floor: "Third Floor", day: "Thursday", time: "11:00 AM" },
    { id: "18", title: "Human-Computer Interaction", room: "M301J", building: "George Moore", floor: "Third Floor", day: "Friday", time: "1:00 PM" },
    { id: "19", title: "Mobile App Development", room: "M301A", building: "George Moore", floor: "Third Floor", day: "Monday", time: "2:00 PM" },
    { id: "20", title: "Cloud Computing", room: "M302", building: "George Moore", floor: "Third Floor", day: "Tuesday", time: "3:00 PM" },
    { id: "21", title: "Operating Systems", room: "M305", building: "George Moore", floor: "Third Floor", day: "Wednesday", time: "9:00 AM" },
    { id: "22", title: "Parallel Computing", room: "M306", building: "George Moore", floor: "Third Floor", day: "Thursday", time: "10:00 AM" },
    { id: "23", title: "Embedded Systems", room: "M307", building: "George Moore", floor: "Third Floor", day: "Friday", time: "11:00 AM" },
    { id: "24", title: "Robotics", room: "M307A", building: "George Moore", floor: "Third Floor", day: "Monday", time: "1:00 PM" },
    { id: "25", title: "Software Testing", room: "M308", building: "George Moore", floor: "Third Floor", day: "Tuesday", time: "2:00 PM" },
    { id: "26", title: "DevOps", room: "M309", building: "George Moore", floor: "Third Floor", day: "Wednesday", time: "3:00 PM" },
    { id: "27", title: "Computer Graphics", room: "M310", building: "George Moore", floor: "Third Floor", day: "Thursday", time: "9:00 AM" },
    { id: "28", title: "Software Architecture", room: "M311", building: "George Moore", floor: "Third Floor", day: "Friday", time: "10:00 AM" },
    { id: "29", title: "UX Design", room: "M312", building: "George Moore", floor: "Third Floor", day: "Monday", time: "11:00 AM" },
    { id: "30", title: "Information Security", room: "M313", building: "George Moore", floor: "Third Floor", day: "Tuesday", time: "1:00 PM" },
    { id: "31", title: "AI Programming", room: "M314", building: "George Moore", floor: "Third Floor", day: "Wednesday", time: "2:00 PM" },
    { id: "32", title: "Innovation Lab", room: "M315", building: "George Moore", floor: "Third Floor", day: "Thursday", time: "3:00 PM" },
    { id: "33", title: "Entrepreneurship Seminar", room: "M316A", building: "George Moore", floor: "Third Floor", day: "Friday", time: "9:00 AM" },
    { id: "34", title: "Project Management", room: "M318", building: "George Moore", floor: "Third Floor", day: "Monday", time: "10:00 AM" },
    { id: "35", title: "AI Workshop", room: "M320A", building: "George Moore", floor: "Third Floor", day: "Tuesday", time: "11:00 AM" },
    { id: "36", title: "Innovation Strategies", room: "M320B", building: "George Moore", floor: "Third Floor", day: "Wednesday", time: "1:00 PM" },
    { id: "37", title: "Data Analytics", room: "M320C", building: "George Moore", floor: "Third Floor", day: "Thursday", time: "2:00 PM" },
    { id: "38", title: "Entrepreneurial Finance", room: "M321", building: "George Moore", floor: "Third Floor", day: "Friday", time: "3:00 PM" },
    { id: "39", title: "European Project Semester", room: "M324", building: "George Moore", floor: "Third Floor", day: "Monday", time: "9:00 AM" },
    { id: "40", title: "European Project Semester", room: "M324A", building: "George Moore", floor: "Third Floor", day: "Tuesday", time: "10:00 AM" },
    { id: "41", title: "European Project Semester", room: "M325", building: "George Moore", floor: "Third Floor", day: "Wednesday", time: "11:00 AM" },
    { id: "42", title: "European Project Semester", room: "M326", building: "George Moore", floor: "Third Floor", day: "Thursday", time: "1:00 PM" },
    { id: "43", title: "European Project Semester", room: "M329", building: "George Moore", floor: "Third Floor", day: "Friday", time: "2:00 PM" },
    { id: "44", title: "European Project Semester", room: "M330", building: "George Moore", floor: "Third Floor", day: "Monday", time: "3:00 PM" },
    { id: "45", title: "European Project Semester", room: "M375C", building: "George Moore", floor: "Third Floor", day: "Tuesday", time: "9:00 AM" }
];